const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const HtmlInlineScriptPlugin = require('html-inline-script-webpack-plugin');

const list = [
	{name: '1942', title: '1942', width: 224, height: 256},
	{name: 'balloon_bomber', title: 'Balloon Bomber', width: 224, height: 256},
	{name: 'baraduke', title: 'Baraduke', width: 288, height: 224},
	{name: 'blast_off', title: 'Blast Off', width: 224, height: 288},
	{name: 'bosconian', title: 'Bosconian', width: 285, height: 224},
	{name: 'chackn_pop', title: 'Chack\'n Pop', width: 256, height: 224},
	{name: 'choplifter', title: 'Choplifter', width: 256, height: 224},
	{name: 'cotton', title: 'Cotton', width: 320, height: 224},
	{name: 'crazy_balloon', title: 'Crazy Balloon', width: 224, height: 256},
	{name: 'crush_roller', title: 'Crush Roller', width: 224, height: 288},
	{name: 'digdug', title: 'DigDug', width: 224, height: 288},
	{name: 'digdug_ii', title: 'DigDug II', width: 224, height: 288},
	{name: 'dragon_buster', title: 'Dragon Buster', width: 288, height: 224},
	{name: 'dragon_spirit', title: 'Dragon Spirit', width: 224, height: 288},
	{name: 'elevator_action', title: 'Elevator Action', width: 256, height: 224},
	{name: 'fantasy_zone', title: 'Fantasy Zone', width: 320, height: 224},
	{name: 'frogger', title: 'Frogger', width: 224, height: 256},
	{name: 'galaga', title: 'Galaga', width: 224, height: 288},
	{name: 'galaga_88', title: 'Galaga \'88', width: 224, height: 288},
	{name: 'galaxian', title: 'Galaxian', width: 224, height: 256},
	{name: 'galaxy_wars', title: 'Galaxy Wars', width: 224, height: 256},
	{name: 'gaplus', title: 'Gaplus', width: 224, height: 288},
	{name: 'genpei_toumaden', title: 'Genpei ToumaDen', width: 288, height: 224},
	{name: 'golden_axe', title: 'Golden Axe', width: 320, height: 224},
	{name: 'gradius', title: 'Gradius', width: 256, height: 224},
	{name: 'grobda', title: 'Grobda', width: 224, height: 288},
	{name: 'hopping_mappy', title: 'Hopping Mappy', width: 288, height: 224},
	{name: 'jr_pac-man', title: 'Jr. Pac-Man', width: 224, height: 288},
	{name: 'jump_bug', title: 'Jump Bug', width: 224, height: 256},
	{name: 'king_and_balloon', title: 'King & Balloon', width: 224, height: 256},
	{name: 'korosuke_roller', title: 'Korosuke Roller', width: 224, height: 288},
	{name: 'libble_rabble', title: 'Libble Rabble', width: 288, height: 224},
	{name: 'lunar_rescue', title: 'Lunar Rescue', width: 224, height: 256},
	{name: 'mahjong_pon_chin_kan', title: 'Mahjong Pon Chin Kan', width: 300, height: 224},
	{name: 'mahjong_yuugi', title: 'Mahjong Yuugi', width: 300, height: 224},
	{name: 'makai-mura', title: 'Makai-Mura', width: 256, height: 224},
	{name: 'mappy', title: 'Mappy', width: 224, height: 288},
	{name: 'marchen_maze', title: 'Marchen Maze', width: 288, height: 224},
	{name: 'metro-cross', title: 'Metro-Cross', width: 288, height: 224},
	{name: 'moon_cresta', title: 'Moon Cresta', width: 224, height: 256},
	{name: 'motos', title: 'Motos', width: 224, height: 288},
	{name: 'new_rally-x', title: 'New Rally-X', width: 285, height: 224},
	{name: 'ninja_princess', title: 'Ninja Princess', width: 256, height: 224},
	{name: 'pac-land', title: 'Pac-Land', width: 288, height: 224},
	{name: 'pac-man', title: 'Pac-Man', width: 224, height: 288},
	{name: 'pac-mania', title: 'Pac-Mania', width: 224, height: 288},
	{name: 'pac_and_pal', title: 'Pac & Pal', width: 224, height: 288},
	{name: 'pengo', title: 'Pengo', width: 224, height: 288},
	{name: 'phozon', title: 'Phozon', width: 224, height: 288},
	{name: 'polaris', title: 'Polaris', width: 224, height: 256},
	{name: 'rally-x', title: 'Rally-X', width: 285, height: 224},
	{name: 'royal_mahjong', title: 'Royal Mahjong', width: 256, height: 240},
	{name: 'salamander', title: 'Salamander', width: 256, height: 224},
	{name: 'scramble', title: 'Scramble', width: 224, height: 256},
	{name: 'sea_fighter_poseidon', title: 'Sea Fighter Poseidon', width: 256, height: 224},
	{name: 'senjou_no_ookami', title: 'Senjou no Ookami', width: 224, height: 256},
	{name: 'sky_kid', title: 'Sky Kid', width: 288, height: 224},
	{name: 'sky_kid_deluxe', title: 'Sky Kid Deluxe', width: 288, height: 224},
	{name: 'souko_ban_deluxe', title: 'Souko Ban Deluxe', width: 288, height: 224},
	{name: 'space_chaser', title: 'Space Chaser', width: 224, height: 256},
	{name: 'space_invaders', title: 'Space Invaders', width: 224, height: 256},
	{name: 'space_laser', title: 'Space Laser', width: 224, height: 256},
	{name: 'star_force', title: 'Star Force', width: 224, height: 256},
	{name: 'strategy_x', title: 'Strategy X', width: 256, height: 224},
	{name: 'sukeban_jansi_ryuko', title: 'Sukeban Jansi Ryuko', width: 320, height: 224},
	{name: 'super_pac-man', title: 'Super Pac-Man', width: 224, height: 288},
	{name: 'super_real_mahjong_part2', title: 'Super Real Mahjong Part 2', width: 300, height: 224},
	{name: 'super_real_mahjong_part3', title: 'Super Real Mahjong Part 3', width: 300, height: 224},
	{name: 'super_xevious', title: 'Super Xevious', width: 224, height: 288},
	{name: 't.t_mahjong', title: 'T.T Mahjong', width: 256, height: 240},
	{name: 'tank_battalion', title: 'Tank Battalion', width: 224, height: 256},
	{name: 'tank_force', title: 'Tank Force', width: 288, height: 224},
	{name: 'tetris', title: 'Tetris', width: 320, height: 224},
	{name: 'the_return_of_ishtar', title: 'The Return of Ishtar', width: 288, height: 224},
	{name: 'the_tower_of_druaga', title: 'The Tower of Druaga', width: 224, height: 288},
	{name: 'time_pilot', title: 'Time Pilot', width: 224, height: 256},
	{name: 'time_pilot_84', title: 'Time Pilot \'84', width: 224, height: 256},
	{name: 'time_tunnel', title: 'Time Tunnel', width: 256, height: 224},
	{name: 'toki_no_senshi', title: 'Toki no Senshi', width: 224, height: 256},
	{name: 'toypop', title: 'Toypop', width: 288, height: 224},
	{name: 'twinbee', title: 'TwinBee', width: 224, height: 256},
	{name: 'ufo_senshi_yohko_chan', title: 'Ufo Senshi Yohko Chan', width: 256, height: 224},
	{name: 'vulgus', title: 'Vulgus', width: 224, height: 256},
	{name: 'warp_and_warp', title: 'Warp & Warp', width: 224, height: 272},
	{name: 'wonder_boy', title: 'Wonder Boy', width: 256, height: 224},
	{name: 'wonder_boy_iii', title: 'Wonder Boy III', width: 320, height: 224},
	{name: 'wonder_boy_in_monster_land', title: 'Wonder Boy in Monster Land', width: 256, height: 224},
	{name: 'wonder_momo', title: 'Wonder Momo', width: 288, height: 224},
	{name: 'world_court', title: 'World Court', width: 288, height: 224},
	{name: 'xevious', title: 'Xevious', width: 224, height: 288},
	{name: 'zigzag', title: 'Zig Zag', width: 224, height: 256},
];
const list2 = [
	{name: 'sound_test', title: 'Sound Test'},
	{name: 'sound_test2', title: 'Sound Test 2'},
	{name: 'sound_test3', title: 'Sound Test 3'},
	{name: 'sound_test4', title: 'Sound Test 4'},
	{name: 'sound_test5', title: 'Sound Test 5'},
	{name: 'sound_test5a', title: 'Sound Test 5a'},
	{name: 'sound_test6', title: 'Sound Test 6'},
	{name: 'sound_test7', title: 'Sound Test 7'},
	{name: 'sound_test8', title: 'Sound Test 8'},
	{name: 'sound_test8a', title: 'Sound Test 8a'},
	{name: 'sound_test8b', title: 'Sound Test 8b'},
	{name: 'sound_test9', title: 'Sound Test 9'},
	{name: 'sound_test9a', title: 'Sound Test 9a'},
	{name: 'sound_test9b', title: 'Sound Test 9b'},
	{name: 'sound_test9c', title: 'Sound Test 9c'},
	{name: 'sound_test10', title: 'Sound Test 10'},
	{name: 'sound_test10a', title: 'Sound Test 10a'},
	{name: 'sound_test10b', title: 'Sound Test 10b'},
	{name: 'sound_test10c', title: 'Sound Test 10c'},
	{name: 'sound_test10d', title: 'Sound Test 10d'},
	{name: 'sound_test10e', title: 'Sound Test 10e'},
	{name: 'sound_test11', title: 'Sound Test 11'},
	{name: 'sound_test11a', title: 'Sound Test 11a'},
	{name: 'sound_test11b', title: 'Sound Test 11b'},
	{name: 'sound_test11c', title: 'Sound Test 11c'},
	{name: 'sound_test12', title: 'Sound Test 12'},
	{name: 'sound_test12a', title: 'Sound Test 12a'},
	{name: 'sound_test12b', title: 'Sound Test 12b'},
	{name: 'sound_test12c', title: 'Sound Test 12c'},
	{name: 'sound_test12d', title: 'Sound Test 12d'},
	{name: 'sound_test12e', title: 'Sound Test 12e'},
	{name: 'sound_test12f', title: 'Sound Test 12f'},
	{name: 'sound_test12g', title: 'Sound Test 12g'},
	{name: 'sound_test12h', title: 'Sound Test 12h'},
	{name: 'sound_test13', title: 'Sound Test 13'},
	{name: 'sound_test13a', title: 'Sound Test 13a'},
	{name: 'sound_test14', title: 'Sound Test 14'},
	{name: 'sound_test15', title: 'Sound Test 15'},
	{name: 'sound_test16', title: 'Sound Test 16'},
	{name: 'sound_test16a', title: 'Sound Test 16a'},
	{name: 'sound_test16b', title: 'Sound Test 16b'},
	{name: 'sound_test16c', title: 'Sound Test 16c'},
	{name: 'sound_test17', title: 'Sound Test 17'},
	{name: 'sound_test18', title: 'Sound Test 18'},
	{name: 'sound_test19', title: 'Sound Test 19'},
	{name: 'sound_test20', title: 'Sound Test 20'},
];
const list3 = [
	{name: 'after_burner_ii_x68', title: 'Afterburner II'},
	{name: 'arkanoid_revenge_of_doh_x68', title: 'Arkanoid Revenge of Doh'},
	{name: 'battle_chess_x68', title: 'Battle Chess'},
	{name: 'bomber_man_x68', title: 'Bomber Man'},
	{name: 'bonanza_bros_x68', title: 'Bonanza Bros'},
	{name: 'bosconian_x68', title: 'Bosconian'},
	{name: 'bubble_bobble_x68', title: 'Bubble Bobble'},
	{name: 'cameltry_x68', title: 'Cameltry'},
	{name: 'cotton_x68', title: 'Cotton'},
	{name: 'd_return_x68', title: 'D_Return'},
	{name: 'daimakaimura_x68', title: 'Daimakaimura'},
	{name: 'dash_yarou_x68', title: 'Dash Yarou'},
	{name: 'detana_twinbee_x68', title: 'Detana!! TwinBee'},
	{name: 'downtown_nekketsu_monogatari_x68', title: 'Downtown Nekketsu Monogatari'},
	{name: 'dragon_spirit_x68', title: 'Dragon Spirit'},
	{name: 'fantasy_zone_x68', title: 'Fantasy Zone'},
	{name: 'galaga_88_x68', title: 'Galaga \'88'},
	{name: 'gemini_wing_x68', title: 'Gemini Wing'},
	{name: 'genocide_x68', title: 'Genocide'},
	{name: 'genocide2_x68', title: 'Genocide 2'},
	{name: 'genpei_toumaden_x68', title: 'Genpei ToumaDen'},
	{name: 'gradius_x68', title: 'Gradius'},
	{name: 'hishou_zame_x68', title: 'Hishou Zame'},
	{name: 'image_fight_x68', title: 'Image Fight'},
	{name: 'lagoon_x68', title: 'Lagoon'},
	{name: 'marble_madness_x68', title: 'Marble Madness'},
	{name: 'marchen_maze_x68', title: 'Marchen Maze'},
	{name: 'namco_video_game_music_library_x68', title: 'Namco Video Game Music Library Vol.1'},
	{name: 'pac-mania_x68', title: 'Pac-Mania'},
	{name: 'parodius_da_x68', title: 'Parodius DA!'},
	{name: 'phalanx_x68', title: 'Phalanx'},
	{name: 'pinball_pinball_x68', title: 'Pinball Pinball'},
	{name: 'populous_x68', title: 'Populous'},
	{name: 'power_league_x68', title: 'Power League'},
	{name: 'prince_of_persia_x68', title: 'Prince of Persia'},
	{name: 'professional_mahjong_gokuu_x68', title: 'Professional Mahjong Gokuu'},
	{name: 'puzznic_x68', title: 'Puzznic'},
	{name: 'quarth_x68', title: 'Quarth'},
	{name: 'r-type_x68', title: 'R-Type'},
	{name: 'shanghai_x68', title: 'Shanghai'},
	{name: 'shuffle_puck_cafe_x68', title: 'Shufflepuck Cafe'},
	{name: 'souko_ban_perfect_x68', title: 'Souko Ban Perfect'},
	{name: 'space_harrier_x68', title: 'Space Harrier'},
	{name: 'super_hang-on_x68', title: 'Super Hang-On'},
	{name: 'super_real_mahjong_pii_and_piii_x68', title: 'スーパーリアル麻雀PII＆PIII'},
	{name: 'syvalion_x68', title: 'Syvalion'},
	{name: 'the_fairyland_story_x68', title: 'The Fairyland Story'},
	{name: 'the_newzealand_story_x68', title: 'The New Zealand Story'},
	{name: 'the_return_of_ishtar_x68', title: 'The Return of Ishtar'},
	{name: 'thunder_force_ii_x68', title: 'Thunder Force II'},
	{name: 'twinbee_x68', title: 'TwinBee'},
	{name: 'vball_x68', title: 'U.S. Championship V\'ball'},
	{name: 'wings_x68', title: 'Wings'},
	{name: 'world_court_x68', title: 'World Court'},
	{name: 'world_stadium_x68', title: 'World Stadium'},
];

module.exports = {
	mode: 'production',
	entry: list.concat(list2).concat(list3).reduce((a, b) => Object.assign(a, {[b.name]: `./${b.name}.js`}), {}),
	output: {
		filename: '[name].bundle.js',
		path: path.resolve(__dirname, 'dist'),
	},
	devServer: {contentBase: path.resolve(__dirname, 'dist')},
	plugins: [].concat(
		list.map(e => new HtmlWebpackPlugin({
			filename: `${e.name}.html`,
			template: 'index.html',
			chunks: [e.name],
			title: e.title,
			width: e.width,
			height: e.height,
			inlineSource: '.js$',
			inject: 'body',
		})),
		list2.map(e => new HtmlWebpackPlugin({
			filename: `${e.name}.html`,
			template: 'sound_test.html',
			chunks: [e.name],
			title: e.title,
			inlineSource: '.js$',
			inject: 'body',
		})),
		list3.map(e => new HtmlWebpackPlugin({
			filename: `${e.name}.html`,
			template: 'x68000.html',
			chunks: [e.name],
			title: e.title,
			inlineSource: '.js$',
			inject: 'body',
		})),
		new HtmlInlineScriptPlugin(),
	),
	module: {
		rules: [{
			test: /\.js$/,
			exclude: /node_modules/,
		}]
	},
};

